const { SlashCommandBuilder, EmbedBuilder } = require('discord.js')

module.exports = {
    data: new SlashCommandBuilder()
    .setName('set time zone')
    .setDescription("Set your timezone for auto converting messages.")
    .addStringOption((option) =>
        option.setName('timezone')
        .setDescription('The region to which you reside.')
        .setRequired(true)
        .addChoices(
            {name: 'ACDT - Australian Central Daylight Savings Time', value: 'ACDT'},
            {name: 'ACST - Australian Central Standard Time', value: 'ACST'},
            {name: 'ACT - Acre Time', value: 'ACT'},
            {name: 'ACWST - Australian Central Western Standard Time', value: 'ACWST'},
            {name: 'ADT - Atlantic Daylight Time', value: 'ADT'},
            {name: 'AEDT - Australian Eastern Daylight Savings Time', value: 'AEDT'},
            {name: 'AEST - Australian Eastern Standard Time', value: 'AEST'},
            {name: 'AFT - Afghanistan Time', value: 'AFT'},
            {name: 'AKDT - Alaska Daylight Time', value: 'AKDT'},
            {name: 'AKST - Alaska Standard Time', value: 'AKST'},
            {name: 'AMST - Amazon Summer Time', value: 'AMST'},
            {name: 'AMT - Amazon Time', value: 'AMT'},
            {name: 'AMT - Armenia Time', value: 'AMT'},
            {name: 'ART - Argentina Time', value: 'ART'},
            {name: 'AST - Atlantic Standard Time', value: 'AST'},
            {name: 'AST - Arabia Standard Time', value: 'AST'},
            {name: 'AT - Atlantic Time', value: 'AT'},
            {name: 'AWST - Australian Western Standard Time', value: 'AWST'},
            {name: 'AZOST - Azores Summer Time', value: 'AZOST'},
            {name: 'AZOT - Azores Standard Time', value: 'AZOT'},
            {name: 'AZT - Azerbaijan Time', value: 'AZT'},
            {name: 'BDT - Brunei Time', value: 'BDT'},
            {name: 'BIT - Baker Island Time', value: 'BIT'},
            {name: 'BNT - Brunei Darussalam Time', value: 'BNT'},
            {name: 'BOT - Bolivia Time', value: 'BOT'},
            {name: 'BRST - Brasilia Summer Time', value: 'BRST'},
            {name: 'BRT - Brasilia Time', value: 'BRT'},
            {name: 'BST - British Summer Time', value: 'BST'},
            {name: 'BST - Bangladesh Standard Time', value: 'BST'},
            {name: 'BST - Bougainville Standard Time', value: 'BST'},
            {name: 'BTT - Bhutan Time', value: 'BTT'},
            {name: 'CAT - Central Africa Time', value: 'CAT'},
            {name: 'CCT - Cocos Islands Time', value: 'CCT'},
            {name: 'CDT - Central Daylight Time', value: 'CDT'},
            {name: 'CDT - Cuba Daylight Time', value: 'CDT'},
            {name: 'CEST - Central European Summer Time', value: 'CEST'},
            {name: 'CET - Central European Time', value: 'CET'},
            {name: 'CHADT - Chatham Daylight Time', value: 'CHADT'},
            {name: 'CHAST - Chatham Standard Time', value: 'CHAST'},
            {name: 'CHOST - Choibalsan Summer Time', value: 'CHOST'},
            {name: 'CHOT - Choibalsan Standard Time', value: 'CHOT'},
            {name: 'CHST - Chamorro Standard Time', value: 'CHST'},
            {name: 'CHUT - Chuuk Time', value: 'CHUT'},
            {name: 'CIST - Clipperton Island Standard Time', value: 'CIST'},
            {name: 'CIT - Central Indonesia Time', value: 'CIT'},
            {name: 'CKT - Cook Island Time', value: 'CKT'},
            {name: 'CLST - Chile Summer Time', value: 'CLST'},
            {name: 'CLT - Chile Standard Time', value: 'CLT'},
            {name: 'COST - Colombia Summer Time', value: 'COST'},
            {name: 'COT - Colombia Time', value: 'COT'},
            {name: 'CST - Central Standard Time', value: 'CST'},
            {name: 'CST - Cuba Standard Time', value: 'CST'},
            {name: 'CST - China Standard Time', value: 'CST'},
            {name: 'CT - Central Time', value: 'CT'},
            {name: 'CVT - Cape Verde Time', value: 'CVT'},
            {name: 'CWST - Central Western Standard Time', value: 'CWST'},
            {name: 'CXT - Christmas Island Time', value: 'CXT'},
            {name: 'DAVT - Davis Time', value: 'DAVT'},
            {name: 'DDUT - Dumont d\'Urville Time', value: 'DDUT'},
            {name: 'EASST - Easter Island Summer Time', value: 'EASST'},
            {name: 'EAST - Easter Island Standard Time', value: 'EAST'},
            {name: 'EAT - East Africa Time', value: 'EAT'},
            {name: 'ECT - Ecuador Time', value: 'ECT'},
            {name: 'EDT - Eastern Daylight Time', value: 'EDT'},
            {name: 'EEST - Eastern European Summer Time', value: 'EEST'},
            {name: 'EET - Eastern European Time', value: 'EET'},
            {name: 'EGST - Eastern Greenland Summer Time', value: 'EGST'},
            {name: 'EGT - Eastern Greenland Time', value: 'EGT'},
            {name: 'EIT - Eastern Indonesian Time', value: 'EIT'},
            {name: 'EST - Eastern Standard Time', value: 'EST'},
            {name: 'ET - Eastern Time', value: 'ET'},
            {name: 'FET - Further-eastern European Time', value: 'FET'},
            {name: 'FJT - Fiji Time', value: 'FJT'},
            {name: 'FKST - Falkland Islands Summer Time', value: 'FKST'},
            {name: 'FKT - Falkland Islands Time', value: 'FKT'},
            {name: 'FNT - Fernando de Noronha Time', value: 'FNT'},
            {name: 'GALT - Galapagos Time', value: 'GALT'},
            {name: 'GAMT - Gambier Islands', value: 'GAMT'},
            {name: 'GET - Georgia Standard Time', value: 'GET'},
            {name: 'GFT - French Guiana Time', value: 'GFT'},
            {name: 'GILT - Gilbert Island Time', value: 'GILT'},
            {name: 'GIT - Gambier Island Time', value: 'GIT'},
            {name: 'GMT - Greenwich Mean Time', value: 'GMT'},
            {name: 'GST - Gulf Standard Time', value: 'GST'},
            {name: 'GST - South Georgia Time', value: 'GST'},
            {name: 'GYT - Guyana Time', value: 'GYT'},
            {name: 'HADT - Hawaii-Aleutian Daylight Time', value: 'HADT'},
            {name: 'HAST - Hawaii-Aleutian Standard Time', value: 'HAST'},
            {name: 'HKT - Hong Kong Time', value: 'HKT'},
            {name: 'HMT - Heard and McDonald Islands Time', value: 'HMT'},
            {name: 'HOVST - Khovd Summer Time', value: 'HOVST'},
            {name: 'HOVT - Khovd Standard Time', value: 'HOVT'},
            {name: 'ICT - Indochina Time', value: 'ICT'},
            {name: 'IDT - Israel Daylight Time', value: 'IDT'},
            {name: 'IOT - Indian Chagos Time', value: 'IOT'},
            {name: 'IRDT - Iran Daylight Time', value: 'IRDT'},
            {name: 'IRKT - Irkutsk Time', value: 'IRKT'},
            {name: 'IRST - Iran Standard Time', value: 'IRST'},
            {name: 'IST - Irish Standard Time', value: 'IST'},
            {name: 'IST - India Standard Time', value: 'IST'},
            {name: 'IST - Israel Standard Time', value: 'IST'},
            {name: 'JST - Japan Standard Time', value: 'JST'},
            {name: 'KALT - Kaliningrad Time', value: 'KALT'},
            {name: 'KGT - Kyrgyzstan Time', value: 'KGT'},
            {name: 'KOST - Kosrae Time', value: 'KOST'},
            {name: 'KRAT - Krasnoyarsk Time', value: 'KRAT'},
            {name: 'KST - Korea Standard Time', value: 'KST'},
            {name: 'KUYT - Kuybyshev Time', value: 'KUYT'},
            {name: 'LHST - Lord Howe Standard Time', value: 'LHST'},
            {name: 'LINT - Line Islands Time', value: 'LINT'},
            {name: 'MAGT - Magadan Time', value: 'MAGT'},
            {name: 'MART - Marquesas Time', value: 'MART'},
            {name: 'MAWT - Mawson Station Time', value: 'MAWT'},
            {name: 'MDT - Mountain Daylight Time', value: 'MDT'},
            {name: 'MHT - Marshall Islands Time', value: 'MHT'},
            {name: 'MMT - Myanmar Time', value: 'MMT'},
            {name: 'MSK - Moscow Time', value: 'MSK'},
            {name: 'MST - Mountain Standard Time', value: 'MST'},
            {name: 'MST - Myanmar Standard Time', value: 'MST'},
            {name: 'MUT - Mauritius Time', value: 'MUT'},
            {name: 'MVT - Maldives Time', value: 'MVT'},
            {name: 'MYT - Malaysia Time', value: 'MYT'},
            {name: 'NCT - New Caledonia Time', value: 'NCT'},
            {name: 'NDT - Newfoundland Daylight Time', value: 'NDT'},
            {name: 'NFT - Norfolk Time', value: 'NFT'},
            {name: 'NOVST - Novosibirsk Summer Time', value: 'NOVST'},
            {name: 'NOVT - Novosibirsk Time', value: 'NOVT'},
            {name: 'NPT - Nepal Time', value: 'NPT'},
            {name: 'NST - Newfoundland Standard Time', value: 'NST'},
            {name: 'NT - Newfoundland Time', value: 'NT'},
            {name: 'NUT - Niue Time', value: 'NUT'},
            {name: 'NZDT - New Zealand Daylight Time', value: 'NZDT'},
            {name: 'NZST - New Zealand Standard Time', value: 'NZST'},
            {name: 'OMSST - Omsk Summer Time', value: 'OMSST'},
            {name: 'OMST - Omsk Standard Time', value: 'OMST'},
            {name: 'ORAT - Oral Time', value: 'ORAT'},
            {name: 'PDT - Pacific Daylight Time', value: 'PDT'},
            {name: 'PET - Peru Time', value: 'PET'},
            {name: 'PETST - Kamchatka Summer Time', value: 'PETST'},
            {name: 'PETT - Kamchatka Time', value: 'PETT'},
            {name: 'PGT - Papua New Guinea Time', value: 'PGT'},
            {name: 'PHOT - Phoenix Island Time', value: 'PHOT'},
            {name: 'PHT - Philippine Time', value: 'PHT'},
            {name: 'PKT - Pakistan Standard Time', value: 'PKT'},
            {name: 'PMDT - Pierre & Miquelon Daylight Time', value: 'PMDT'},
            {name: 'PMST - Pierre & Miquelon Standard Time', value: 'PMST'},
            {name: 'PONT - Pohnpei Standard Time', value: 'PONT'},
            {name: 'PST - Pacific Standard Time', value: 'PST'},
            {name: 'PST - Pitcairn Standard Time', value: 'PST'},
            {name: 'PT - Pacific Time', value: 'PT'},
            {name: 'PWT - Palau Time', value: 'PWT'},
            {name: 'PYST - Paraguay Summer Time', value: 'PYST'},
            {name: 'PYT - Paraguay Time', value: 'PYT'},
            {name: 'RET - Reunion Time', value: 'RET'},
            {name: 'ROTT - Rothera Time', value: 'ROTT'},
            {name: 'SAKT - Sakhalin Time', value: 'SAKT'},
            {name: 'SAMT - Samara Time', value: 'SAMT'},
            {name: 'SAST - South Africa Standard Time', value: 'SAST'},
            {name: 'SBT - Solomon Islands Time', value: 'SBT'},
            {name: 'SCT - Seychelles Time', value: 'SCT'},
            {name: 'SDT - Samoa Daylight Time', value: 'SDT'},
            {name: 'SGT - Singapore Time', value: 'SGT'},
            {name: 'SLST - Sri Lanka Standard Time', value: 'SLST'},
            {name: 'SRET - Srednekolymsk Time', value: 'SRET'},
            {name: 'SRT - Suriname Time', value: 'SRT'},
            {name: 'SST - Samoa Standard Time', value: 'SST'},
            {name: 'SST - Solomon Islands Time', value: 'SST'},
            {name: 'SYOT - Showa Station Time', value: 'SYOT'},
            {name: 'TAHT - Tahiti Time', value: 'TAHT'},
            {name: 'TFT - Indian Kerguelen Time', value: 'TFT'},
            {name: 'THA - Thailand Standard Time', value: 'THA'},
            {name: 'TJT - Tajikistan Time', value: 'TJT'},
            {name: 'TKT - Tokelau Time', value: 'TKT'},
            {name: 'TLT - East Timor Time', value: 'TLT'},
            {name: 'TMT - Turkmenistan Time', value: 'TMT'},
            {name: 'TOT - Tonga Time', value: 'TOT'},
            {name: 'TRT - Turkey Time', value: 'TRT'},
            {name: 'TVT - Tuvalu Time', value: 'TVT'},
            {name: 'ULAST - Ulaanbaatar Summer Time', value: 'ULAST'},
            {name: 'ULAT - Ulaanbaatar Standard Time', value: 'ULAT'},
            {name: 'UTC - Coordinated Universal Time', value: 'UTC'},
            {name: 'UYST - Uruguay Summer Time', value: 'UYST'},
            {name: 'UYT - Uruguay Standard Time', value: 'UYT'},
            {name: 'UZT - Uzbekistan Time', value: 'UZT'},
            {name: 'VET - Venezuelan Standard Time', value: 'VET'},
            {name: 'VET - Venezuelan Standard Time', value: 'VET'},
            {name: 'VOST - Vostok Station Time', value: 'VOST'}, 
            {name: 'VUT - Vanuatu Time', value: 'VUT'}, 
            {name: 'WAKT - Wake Island Time', value: 'WAKT'}, 
            {name: 'WAST - West Africa Summer Time', value: 'WAST'}, 
            {name: 'WAT - West Africa Time', value: 'WAT'}, 
            {name: 'WEST - Western European Summer Time', value: 'WEST'}, 
            {name: 'WET - Western European Time', value: 'WET'}, 
            {name: 'WFT - Wallis and Futuna Time', value: 'WFT'}, 
            {name: 'WGST - West Greenland Time', value: 'WGST'}, 
            {name: 'WGST - West Greenland Summer Time', value: 'WGST'}, 
            {name: 'WIB - Western Indonesia Time', value: 'WIB'}, 
            {name: 'WIT - Eastern Indonesia Time', value: 'WIT'}, 
            {name: 'WST - Western Standard Time', value: 'WST'}, 
            {name: 'YAKT - Yakutsk Time', value: 'YAKT'}, 
            {name: 'YEKT - Yekaterinburg Time', value: 'YEKT'}, 
        ),
    ),
    async execute(interaction, client) {
        const user = interaction.user;
        const desiredTimeZone = interaction.options.getString('timezone');

        if (!(new Date().toLocaleString('en-US', { timeZone: desireTimeZone }))) return await interaction.reply({
            content: `"${desiredTimeZone}" is not a valid timezone`,
            ephemeral: true   
        });
        else {
            const embed = new EmbedBuilder()
                .setTitle(`Time zone for ${user} has updated:`)
                .setTimestamp()
                .addFields([
                    {
                        name: `${desiredTimeZone}`,
                        value: `\u200b`,
                    },
                ])
                .setFooter({
                    text: client.user.tag,
                    iconURL: client.user.displayAvatarURL(),
                });
            await interaction.reply({
                embeds: [embed],
                ephemeral: true,
            })
        }

        const timezone = await client.getTimeZone(user,timezone);
        
    }

}